QuizNetASPKolo/Models/QuizSummaryViewModel.cs
using QuizNetASPKolo.BusinessLogic.DTOs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuizNetASPKolo.Models
{
    public class QuizSummaryViewModel
    {
        public List<QuestionDto> Questions { get; set; }
        public int[] UserAnswersIds { get; set; }
        public int CorrectAnswers { get; set; }
        public double PercentageCorrect
        {
            get
            {
                return 100 * (double)CorrectAnswers / Questions.Count();
            }
        }

        public string SummaryText
        {
            get
            {
                return PercentageCorrect > 50 ? "Well done!" : "Bummer!";
            }
        }

        public string ProgressBarColor
        {
            get
            {
                return PercentageCorrect > 50 ? "bg-success" : "bg-danger";
            }
        }

        public string ClassNamesForAnswer(AnswerDto answer, int userAnswerIndex)
        {
            if (answer.IsCorrect)
            {
                return "list-group-item-success";
            }
            
            if (UserAnswersIds[userAnswerIndex] == answer.Id)
            {
                return "list-group=item-danger";
            }

            return string.Empty;
        }
    }
}

QuizNetASPKolo/Models/QuizViewModel.cs
using QuizNetASPKolo.BusinessLogic.DTOs;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace QuizNetASPKolo.Models
{
    public class QuizViewModel
    {
        public List<QuestionDto> Questions { get; set; }

        public int[] UserAnswerIds { get; set; }

        public string QuizType { get; set; }

        public QuizViewModel()
        {

        }

        public QuizViewModel(List<QuestionDto> questions, string quizType)
        {
            Questions = questions;
            UserAnswerIds = new int[Questions.Count()];
            QuizType = quizType;
        }
    }
}

QuizNetASPKolo/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using QuizNetASPKolo.BusinessLogic;
using QuizNetASPKolo.BusinessLogic.DTOs;
using QuizNetASPKolo.BusinessLogic.Interfaces;
using QuizNetASPKolo.Models;
using QuizNetDataAccess;
using QuizNetDataAccess.Models;

namespace QuizNetASPKolo.Controllers
{
    public class QuestionController : Controller
    {

        private readonly IQuizService _quizService;

        private readonly IQuestionService _questionService;


        public QuestionController(IQuizService quizService, IQuestionService questionService)
        {
            _quizService = quizService;
            _questionService = questionService;
        }

        [ResponseCache(Duration = 120, Location = ResponseCacheLocation.Client)]
        public IActionResult GetAll()
        {
            var questions = _questionService.GetAll();
            return View(questions);
        }

        public IActionResult Get(int id)
        {
            var question = _questionService.GetById(id);
            return View(question);
        }

        public IActionResult Delete(int id)
        {
            _questionService.Delete(id);
            return RedirectToAction("GetAll");
        }

        public IActionResult Create()
        {
            QuestionFormViewModel newQuestion = new QuestionFormViewModel();
            return View("QuestionForm", newQuestion);
        }

        public IActionResult Update(int id)
        {
            QuestionDto editedQuestion = _questionService.GetById(id);
            QuestionFormViewModel newEditedQuestion = new QuestionFormViewModel(editedQuestion);
            return View("QuestionForm", newEditedQuestion);
        }

        [HttpPost]
        public IActionResult Save(QuestionFormViewModel viewModel)
        {
            if (!ModelState.IsValid)
            {
                return View("QuestionForm", viewModel);
            }

            var question = viewModel.Question;
            question.Answers[viewModel.CorrectAnswerIndex].IsCorrect = true;

            if (question.Id == 0)
            {
                question = _questionService.Add(question);
            }
            else
            {
                _questionService.Update(question);
            }

            return RedirectToAction("Get", new { Id = question.Id });
        }

        [Route("{controller}/{action}/{quizType}")]
        public IActionResult GenerateQuiz(string quizType)
        {
            List<QuestionDto> quiz = new List<QuestionDto>();
            if (quizType == "recent")
            {
                quiz = _quizService.GenerateRecentlyAddedQuestionsQuiz();
            }
            else if (quizType == "random")
            {
                quiz = _quizService.GenerateQuiz();
            }
            else
            {
                return RedirectToAction("GetAll");
            }

            var quizViewModel = new QuizViewModel(quiz, quizType);
            return View("Quiz", quizViewModel);
        }

        [HttpPost]
        public IActionResult CheckQuiz(QuizViewModel viewModel)
        {
            var userAnswersIds = viewModel.UserAnswerIds;
            var correctAnswers = _quizService.CheckQuiz(viewModel.Questions, userAnswersIds);

            var summaryViewModel = new QuizSummaryViewModel()
            {
                Questions = viewModel.Questions,
                UserAnswersIds = viewModel.UserAnswerIds,
                CorrectAnswers = correctAnswers
            };

            return View("QuizSummary", summaryViewModel);
        }
    }
}

QuizNetASPKolo/Views/Question/Get.cshtml
@model QuizNetASPKolo.BusinessLogic.DTOs.QuestionDto
@{
    ViewData["Title"] = "Get";
}

<a class="btn btn-info" asp-controller="Question" asp-action="Update" asp-route-id="@Model.Id">Update</a>
<a class="btn btn-danger" asp-controller="Question" asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
<h1>@Model.Text</h1>
<p>Created at: @Model.CreatedAt.ToString()</p>
<p>Updated at: @Model.UpdatedAt.ToString()</p>
<ul>
    <ul class="list-group">
        @for (int i = 0; i < Model.Answers.Length; i++)
        {
            if (Model.Answers[i].IsCorrect)
            {
                <li class="list-group-item active">
                    @Model.Answers[i].Text
                </li>
            }
            else
            {
                <li class="list-group-item">
                    @Model.Answers[i].Text
                </li>
            }
        }
    </ul>
</ul>

QuizNetASPKolo/Views/Question/GetAll.cshtml
@model List<QuizNetASPKolo.BusinessLogic.DTOs.QuestionDto>
@{
    ViewData["Title"] = "GetAll";
}

<div class="modal fade" id="questionsMetadata" data-backdrop="static" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div id="questionInfo">
                    <div class="text-center">
                        <div class="spinner-border text-primary" role="status">
                            <span class="sr-only">Loading</span>
                        </div>
                    </div>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Understood</button>
            </div>
        </div>
    </div>
</div>


<h1>Questions</h1>
<a class="btn btn-primary" asp-controller="Question" asp-action="Create">Create</a>
<a class="btn btn-primary" asp-controller="Question" asp-action="GenerateQuiz" asp-route-quizType="random">Generate random Quiz</a>
<a class="btn btn-primary" asp-controller="Question" asp-action="GenerateQuiz" asp-route-quizType="recent">Generate Quiz with recent questions</a>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#questionsMetadata">
    Show metadata
</button>

<br />
@foreach (var question in Model)
{
    <h3>@question.Text</h3>
    <a class="btn btn-primary" asp-controller="Question" asp-action="Get" asp-route-id="@question.Id">Details</a>
    <a class="btn btn-info" asp-controller="Question" asp-action="Update" asp-route-id="@question.Id">Update</a>
    <a class="btn btn-danger" asp-controller="Question" asp-action="Delete" asp-route-id="@question.Id">Delete</a>
    <ul class="list-group">
        @foreach (var answer in question.Answers)
        {
            <li class="list-group-item">
                @answer.Text
            </li>
        }
    </ul>

}

@section Scripts{
    <script>
        $(document).ready(function() {
            $("#questionMetadata").on("shown.bs.modal",
                function(e) {
                    $.ajax({
                        url: "/api/questionsmetadata",
                        method: "GET",
                        success: function(data) {
                            $("#questionInfo").html("Currently there are " +
                                data.questionsCount +
                                " questions in the database. First question has been added on " +
                                data.oldestQuestion.toLocaleString() +
                                ". Newest question has been added on " +
                                data.newestQuestion);
                        },
                        error: function(error) {
                            console.log(error);
                        }
                    });
                });
        });
    </script>
}

QuizNetASPKolo/Views/Question/QuestionForm.cshtml
@model QuizNetASPKolo.Models.QuestionFormViewModel
@{
    ViewData["Title"] = "QuestionForm";
}

<h1>@Model.ActionType</h1>

<form method="post" asp-controller="Question" asp-action="Save">
    <input type="hidden" asp-for="Question.Id"/>

    Question text:
    <input class="form-control" asp-for="Question.Text" />
    <span asp-validation-for="Question.Text" class="text-danger"></span>

    <div class="form-check">
        Answers 1:
        <input id="answer0" class="form-control" asp-for="Question.Answers[0].Text" />
        <span asp-validation-for="Question.Answers[0].Text" class="text-danger"></span>

        Answers 2:
        <input id="answer1" class="form-control" asp-for="Question.Answers[1].Text" />
        <span asp-validation-for="Question.Answers[1].Text" class="text-danger"></span>

        Answers 3:
        <input id="answer2" class="form-control" asp-for="Question.Answers[2].Text" />
        <span asp-validation-for="Question.Answers[2].Text" class="text-danger"></span>

        Answers 4:
        <input id="answer3" class="form-control" asp-for="Question.Answers[3].Text" />
        <span asp-validation-for="Question.Answers[3].Text" class="text-danger"></span>
    </div>

    <select class="custom-select" asp-for="CorrectAnswerIndex">
        <option value="0" id="0" selected>#1</option>
        <option value="1" id="1">#2</option>
        <option value="2" id="2">#3</option>
        <option value="3" id="3">#4</option>
    </select>
    <button class="btn btn-primary" type="submit">@Model.ActionType</button>
</form>

@section Scripts{ 
    <script>
        $(document).ready(function () {
            for (var i = 0; i < 4; i++) {
                $("#answer" + i).on("input",
                function (e) {
                    var enteredText = e.target.value;
                    $("#" + i).html(enteredText);
                });
            }
            
        });
    </script>
}

QuizNetASPKolo/Views/Question/Quiz.cshtml
@model QuizNetASPKolo.Models.QuizViewModel
@{
    ViewData["Title"] = "Quiz";
}

<h1>Generated Quiz</h1>
<h6 class="mb-4">(based on @Model.QuizType questions)</h6>

<br />
<hr />

<form method="post" asp-controller="Question" asp-action="CheckQuiz">
    @for (int i = 0; i < Model.Questions.Count(); i++)
	{
        <div class="mb-3">
            @Model.Questions[i].Text
            <input type="hidden" asp-for="Questions[i].Id"/>

            @for (int j = 0; j < Model.Questions[i].Answers.Length; j++)
            {
                <div class="form-check">
                    <input id="q@(i)_a@(j)" class="form-check-input" type="radio" asp-for="UserAnswerIds[i]" value="@Model.Questions[i].Answers[j].Id"/>
                    <label class="form-check-label" for="q@(i)_a@(j)">
                        @Model.Questions[i].Answers[j].Text
                    </label>
                </div>
            }
        </div>
	}
    <hr />
    <button class="btn btn-primary" type="submit">Check my results</button>
</form>

QuizNetASPKolo/Views/Question/QuizSummary.cshtml
@model QuizNetASPKolo.Models.QuizSummaryViewModel
@{
    ViewData["Title"] = "QuizSummary";
}

<h1>QuizSummary</h1>

<h2>@Model.SummaryText You had @Model.CorrectAnswers (@Model.PercentageCorrect.ToString(format: "#.##")%) answers right!</h2>
<div class="progress">
    <div class="progress-bar @Model.ProgressBarColor" role="progressbar" aria-valuemin="0" aria-valuemax="100" style="width: @((int)Model.PercentageCorrect)%"></div>
</div>

@for (int i = 0; i < Model.Questions.Count; i++)
{
    <div class="my-5">
        <h4>@Model.Questions[i].Text</h4>

        <ul class="list-group">
            @for (int j = 0; j < Model.Questions[i].Answers.Length; j++)
			{
			    <li class="list-group-item @Model.ClassNamesForAnswer(Model.Questions[i].Answers[j], i)">@Model.Questions[i].Answers[j].Text</li>
			}
        </ul>
    </div>
}

<a class="btn btn-primary" asp-controller="Questions" asp-action="GetAll">Return to questions</a>